### ISSUE TITLE
PruneCluster and Meteor.js

### ISSUE THREAD

**Issue by n0ne** [SINTEF-9012/PruneCluster#101]
Hi.

I found your package on [Atmosphere.js](https://atmospherejs.com/prunecluster/prunecluster).
Do you plan some improvements? I mean server-side rendering or smth like server-side aggregate? 
What, in your opinion, the best way to send 100,000 markers from Meteor to the client?

**Comment by yellowiscool** [comment]
Hei,

I am not a meteor developer myself, the package has been made by @mordka.

However yes I have some plans to improve the library, especially on client side API. For server-side rendering/aggregation, I have some long terms ideas about using stream processing with big data toys such as Storm or Spark Streaming but it's unclear.

I don't know how Meteor transfers the data (compressed json?) but I successfully used ProtocolBuffer and ProtoBuf.js in my applications. 100 000 markers is not much when serialized in ProtocolBuffer, but if you have a lot of metadata in strings you may want to compress the protocol buffer as well (it might be automatic if you use websockets for example). Also if you use websockets, I recommend using chunks instead of sending each marker separately.

**Comment by n0ne** [comment]
[Here](http://localgeo.meteor.com/) Meteor example with 32951 markers. It is not very fast )-:
And I have no idea, how send chunks in pub/sub schema in Meteor...
