### ISSUE TITLE
Moving marker transition does not work if the distance is long

### ISSUE THREAD

**Issue by bcalik** [SINTEF-9012/PruneCluster#107]
Hello,

When moving a marker, transition animation does not work if the distance is long.
I don't know if this is a feature or not, but there must be an option to disable this behaviour.

Moving short distances working well.

*Edit: Btw I am using 2.0-beta version with leaflet 1.0*

Thank you.

**Comment by yellowiscool** [comment]
Hello, thanks for reporting this issue.

This behaviour is normal with the current version, it due to a technical limitation (the marker moves and teleports from a cluster to another cluster), but we some changes introduced last year make this issue very easy to fix.

I pushed a [new branch](https://github.com/SINTEF-9012/PruneCluster/tree/bugfix-107), that might be merged before the next release if it doesn't break anything. You can try [the compiled file](https://github.com/SINTEF-9012/PruneCluster/blob/bugfix-107/dist/PruneCluster.js).

**Comment by bcalik** [comment]
Thanks for the fast fix!
I will try as soon as possible.

**Comment by bcalik** [comment]
I have just tried and its working well. Thank you.
