### ISSUE TITLE
Question about a lowest cluster population setting

### ISSUE THREAD

**Issue by uygardonduran** [SINTEF-9012/PruneCluster#137]
Hi, I want to learn if it's possible to set a cluster population threshold so that if the cluster population is less than or equal to that limit draw markers, otherwise draw cluster icon. Current implementation works like this limit is set to 1. I'd like to learn if this is doable without a huge code change before digging into your code. Thanks.

**Comment by yellowiscool** [comment]
Hei,

I think it's a difficult and heavy change, because the code is very designed for the current limit of 1. The library has a few technics to improve performances with single markers, and it's not an easy part to change in the source code.

Maybe, you could create a custom cluster icon, that shows markers when the population of the marker isn't to high.

**Comment by uygardonduran** [comment]
Also supposed to draw polygons instead of markers, just overriding BuildLeafletClusterIcon will not be enough I guess. Thanks for your answer.

**Comment by yellowiscool** [comment]
You are welcome :)
