### ISSUE TITLE
Don't restore _removeFlag

### ISSUE THREAD

**Issue by oscarhidalgo** [SINTEF-9012/PruneCluster#32]
If I add two or more arrays of markers to the cluster, when I remove an array their markers are marked with the _removeFlag = true.

If I go back to add this array their markers continue marked with _removeFlag = true and then if I remove other array of markers this array is also removed (their points).

I tried to solve it temporarily with:

			for (i = 0, l = this._markers.length; i < l; ++i) {
				this._markers[i]._removeFlag = false;
			}

before

            for (var i = 0, l = markers.length; i < l; ++i) {
                markers[i]._removeFlag = true;
            }

            var newMarkersList = [];
            for (i = 0, l = this._markers.length; i < l; ++i) {
                if (!this._markers[i]._removeFlag) {
                    newMarkersList.push(this._markers[i]);
                }
            }

            this._markers = newMarkersList;

It solves the problem but sure there's a better way.

**Comment by yellowiscool** [comment]
I close the issue because the _removeFlag is deleted in the [RegisterMarker method](https://github.com/SINTEF-9012/PruneCluster/blob/54a5d252617e9e0a39bec3bf616642224b2c05b9/PruneCluster.ts#L328-L330) and you are using directly the private _markers class member.

However, your solution should work correctly.
