### ISSUE TITLE
more detailed bounds/hull

### ISSUE THREAD

**Issue by StilgarBF** [SINTEF-9012/PruneCluster#51]
A feature in markercluster, that I miss here is the ability to show detailed bounds/hull (area with the inlcuded markers) on mouseover.
cluster.bounds only includes max/min lat and lon which will give me a rectangle.

It would be nice to add a builtin "showBoundsOnMouseover" or at least give access to detailed bounds. 

As an alternative: is it possible to get a list of all included Markers from a cluster, to calculate the confex hull?

**Comment by yellowiscool** [comment]
Hello,

You can find [here](https://github.com/SINTEF-9012/PruneCluster/blob/master/examples/random.10000-getclustermarkers.html#L36-L42) an example of how to get the markers from a cluster. You also need to enable the feature using ```PruneCluster.Cluster.ENABLE_MARKERS_LIST = true;```. It's not enabled by default because it slows down the application.

I have not implemented a showBoundsOnmouseover feature for different reasons :
 
 * Our application is for mobile touch device first, so no mouseover
 * When you have a lot of markers, the hull is more a less a square corresponding to the grid clustering
 * You need to update a hull in real-time when displayed

This feature can definitely be added in the library, but I don't plan developing it.

**Comment by StilgarBF** [comment]
Thanks for the fast response.
got it working now. : http://www.freifunk-karte.de/

I'll close this issue since there are no plans of adding that feature and its no longer an issue for me.

Great work on that Plugin. :-D

**Comment by yellowiscool** [comment]
Hum, it's pretty nice. Can I keep the showClusterHull on the side? I maybe add it as an option when I will have time.

A small issue : if I zoom using the mousewheel, the old clusterArea stays on the map. I think you can check if the clusterArea is still on the map and use setLatLngs instead of creating a new one.

**Comment by StilgarBF** [comment]
You can use whatever part you like.
Thanks for the bugnote - will fix that. I think I will remove that poly on zoom.
