### ISSUE TITLE
why dont extends L.Marker !?

### ISSUE THREAD

**Issue by namezero** [SINTEF-9012/PruneCluster#58]
we loose all events on markers ('on'...) , aslo all existing methods such as bindPopup 
why not ClusterObject.prototype = new L.Marker() ?? 
it will be much better like that ! map.markers.RegisterMarker(new L.Marker(position, opts));

**Comment by yellowiscool** [comment]
Because the main algorithm is totally independent from Leaflet. Leaflet was only used for visualizing the results of the algorithm in the beginning.

Also for performances reasons. PruneCluster.Marker and PruneCluster.Location are faster than L.Marker and L.LatLng. They don't check the inputs and they do the projections (conversions of the WGS84 locations to pixels positions) only when necessary.

However, providing a simular API is in the TODO list.
