### ISSUE TITLE
The constructor is called multiple times?

### ISSUE THREAD

**Issue by valerio-bozzolan** [SINTEF-9012/PruneCluster#69]
I noticed that when I override the `pruneCluster.PrepareLeafletMarker` method, the code in it (for every marker) is called even when zoom changes (when markers have to be re-clustered).

As a consequence if I have set a `click` listener in it, and if I zoom four times, I will have four same listeners on the same markers.

How to avoid this?

**Comment by yellowiscool** [comment]
Hello,

PrepareLeafletMarker is not really a constructor, because the Marker objects are recycled. It's why you can have multiple events on the same marker.

What you can do is using remove the previous listener using ```off``` or ```clearAllEventListeners```. An other solution is using ```hasEventListeners``` to check if the listener already exists and to create the listener only once.

**Comment by valerio-bozzolan** [comment]
Thanks for the quickly clarification!
I chose the `hasEventListeners("click")` way.

**Comment by valerio-bozzolan** [comment]
If the marker has a popup, using ```off``` will remove it's listener. Additionally the ```hasEventListeners("click")``` way obviously will be always ```true``` with that popup listener. So I've set a flag at the end of the marker declaration and I check if it exists at the beginning, in order to ```return``` in that case.

**Comment by yellowiscool** [comment]
Yes, it should be better. It might also be interesting to have something like this flag system by default.
